package integlec;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class hangman extends javax.swing.JFrame {

    /**
     * Creates new form hangman
     */
    public hangman() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    int count = 0;
    List <String> words = Arrays.asList("watch","bottle","router","speaker","monitor");
    Random i = new Random();
    int index = i.nextInt(words.size());
    String guess = words.get(index);

   ArrayList <Character> letterList = new ArrayList <Character>();
   {{
      for(int j = 0; j<guess.length();j++){
              letterList.add(guess.charAt(j));
      }      
    }};
    
    ArrayList <String> underscoreList = new ArrayList <String>();
    {{
            for (int k = 0; k<letterList.size(); k++){
                    underscoreList.add("_");
            }
    }};
    
    //ArrayList <Character> letterList = new ArrayList <Character>();
    

        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                jLabel2 = new javax.swing.JLabel();
                zButton = new javax.swing.JButton();
                xButton = new javax.swing.JButton();
                cButton = new javax.swing.JButton();
                vButton = new javax.swing.JButton();
                bButton = new javax.swing.JButton();
                nButton = new javax.swing.JButton();
                mButton = new javax.swing.JButton();
                lButton = new javax.swing.JButton();
                uButton = new javax.swing.JButton();
                iButton = new javax.swing.JButton();
                oButton = new javax.swing.JButton();
                aButton = new javax.swing.JButton();
                sButton = new javax.swing.JButton();
                dButton = new javax.swing.JButton();
                fButton = new javax.swing.JButton();
                gButton = new javax.swing.JButton();
                hButton = new javax.swing.JButton();
                jButton = new javax.swing.JButton();
                qButton = new javax.swing.JButton();
                wButton = new javax.swing.JButton();
                eButton = new javax.swing.JButton();
                rButton = new javax.swing.JButton();
                tButton = new javax.swing.JButton();
                yButton = new javax.swing.JButton();
                kButton = new javax.swing.JButton();
                pButton = new javax.swing.JButton();
                jButton28 = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geovelle\\Documents\\NetBeansProjects\\integlec\\src\\integlec\\pics\\post.png")); // NOI18N

                zButton.setText("Z");
                zButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                zButtonActionPerformed(evt);
                        }
                });

                xButton.setText("X");
                xButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                xButtonActionPerformed(evt);
                        }
                });

                cButton.setText("C");
                cButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                cButtonActionPerformed(evt);
                        }
                });

                vButton.setText("V");
                vButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                vButtonActionPerformed(evt);
                        }
                });

                bButton.setText("B");
                bButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                bButtonActionPerformed(evt);
                        }
                });

                nButton.setText("N");
                nButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                nButtonActionPerformed(evt);
                        }
                });

                mButton.setText("M");
                mButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                mButtonActionPerformed(evt);
                        }
                });

                lButton.setText("L");
                lButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                lButtonActionPerformed(evt);
                        }
                });

                uButton.setText("U");
                uButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                uButtonActionPerformed(evt);
                        }
                });

                iButton.setText("I");
                iButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                iButtonActionPerformed(evt);
                        }
                });

                oButton.setText("O");
                oButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                oButtonActionPerformed(evt);
                        }
                });

                aButton.setText("A");
                aButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                aButtonActionPerformed(evt);
                        }
                });

                sButton.setText("S");
                sButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                sButtonActionPerformed(evt);
                        }
                });

                dButton.setText("D");
                dButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                dButtonActionPerformed(evt);
                        }
                });

                fButton.setText("F");
                fButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                fButtonActionPerformed(evt);
                        }
                });

                gButton.setText("G");
                gButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                gButtonActionPerformed(evt);
                        }
                });

                hButton.setText("H");
                hButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                hButtonActionPerformed(evt);
                        }
                });

                jButton.setText("J");
                jButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                jButtonActionPerformed(evt);
                        }
                });

                qButton.setText("Q");
                qButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                qButtonActionPerformed(evt);
                        }
                });

                wButton.setText("W");
                wButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                wButtonActionPerformed(evt);
                        }
                });

                eButton.setText("E");
                eButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                eButtonActionPerformed(evt);
                        }
                });

                rButton.setText("R");
                rButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                rButtonActionPerformed(evt);
                        }
                });

                tButton.setText("T");
                tButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                tButtonActionPerformed(evt);
                        }
                });

                yButton.setText("Y");
                yButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                yButtonActionPerformed(evt);
                        }
                });

                kButton.setText("K");
                kButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                kButtonActionPerformed(evt);
                        }
                });

                pButton.setText("P");
                pButton.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                pButtonActionPerformed(evt);
                        }
                });

                jButton28.setText("Start");
                jButton28.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                jButton28ActionPerformed(evt);
                        }
                });

                jLabel1.setText("Word:");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButton28)
                                                                .addGap(164, 164, 164))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(37, 37, 37)))
                                                .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(zButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(xButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(vButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(nButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(mButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(aButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(dButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(fButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(gButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(hButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(kButton)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(qButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(wButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(eButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(yButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(uButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(iButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(oButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pButton)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton28)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 11, Short.MAX_VALUE)
                                                .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(qButton)
                                        .addComponent(wButton)
                                        .addComponent(eButton)
                                        .addComponent(rButton)
                                        .addComponent(tButton)
                                        .addComponent(yButton)
                                        .addComponent(uButton)
                                        .addComponent(iButton)
                                        .addComponent(oButton)
                                        .addComponent(pButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(aButton)
                                        .addComponent(sButton)
                                        .addComponent(dButton)
                                        .addComponent(fButton)
                                        .addComponent(gButton)
                                        .addComponent(hButton)
                                        .addComponent(jButton)
                                        .addComponent(kButton)
                                        .addComponent(lButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(zButton)
                                        .addComponent(xButton)
                                        .addComponent(cButton)
                                        .addComponent(vButton)
                                        .addComponent(bButton)
                                        .addComponent(nButton)
                                        .addComponent(mButton))
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents
    
    public void changeImage(){
        if (count == 1){
            jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geovelle\\Desktop\\HANGMAN\\head.png"));
        }
        else if (count == 2){
            jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geovelle\\Desktop\\HANGMAN\\body.png"));
        }
        else if (count == 3){
            jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geovelle\\Desktop\\HANGMAN\\hand1.png"));
        }
        else if (count == 4){
            jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geovelle\\Desktop\\HANGMAN\\hand2.png"));
        }
        else if (count == 5){
            jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geovelle\\Desktop\\HANGMAN\\foot1.png"));
        }
        else if (count == 6){
            jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geovelle\\Desktop\\HANGMAN\\foot2.png"));
            JOptionPane.showMessageDialog(rootPane, "BOBO "+guess.toUpperCase());
            System.exit(0);
        }
    }
    
    public void isWin(){
            if(!underscoreList.contains("_")){
                    JOptionPane.showMessageDialog(rootPane,"YOU WIN!");
                    System.exit(0);
            }
    }
    
    public void tryAgain(){
        System.out.println("Try again?");
        //JOptionPane.showOptionDialog(this, i, guess, WIDTH, WIDTH, icon, os, i)
    }
    
    private void qButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qButtonActionPerformed
        if(letterList.contains('q')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('q')){
                        underscoreList.set(i, "q");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        qButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_qButtonActionPerformed

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
        if(letterList.contains('a')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('a')){
                        underscoreList.set(i, "a");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        aButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_aButtonActionPerformed

    private void oButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oButtonActionPerformed
        if(letterList.contains('o')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('o')){
                        underscoreList.set(i, "o");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        oButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_oButtonActionPerformed

    private void wButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wButtonActionPerformed
        if(letterList.contains('w')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('w')){
                        underscoreList.set(i, "w");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        wButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_wButtonActionPerformed

    private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eButtonActionPerformed
        if(letterList.contains('e')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('e')){
                        underscoreList.set(i, "e");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        eButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_eButtonActionPerformed

    private void rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonActionPerformed
        if(letterList.contains('r')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('r')){
                        underscoreList.set(i, "r");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        rButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_rButtonActionPerformed

    private void tButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonActionPerformed
        if(letterList.contains('t')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('t')){
                        underscoreList.set(i, "t");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        tButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_tButtonActionPerformed

    private void yButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yButtonActionPerformed
        if(letterList.contains('y')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('y')){
                        underscoreList.set(i, "y");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        yButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_yButtonActionPerformed

    private void uButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uButtonActionPerformed
        if(letterList.contains('u')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('u')){
                        underscoreList.set(i, "u");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        uButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_uButtonActionPerformed

    private void iButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iButtonActionPerformed
        if(letterList.contains('i')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('i')){
                        underscoreList.set(i, "i");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        iButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_iButtonActionPerformed

    private void pButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButtonActionPerformed
        if(letterList.contains('p')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('p')){
                        underscoreList.set(i, "p");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        pButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_pButtonActionPerformed

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        if(letterList.contains('s')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('s')){
                        underscoreList.set(i, "s");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        sButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_sButtonActionPerformed

    private void dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dButtonActionPerformed
        if(letterList.contains('d')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('d')){
                        underscoreList.set(i, "d");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        dButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_dButtonActionPerformed

    private void fButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonActionPerformed
        if(letterList.contains('f')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('f')){
                        underscoreList.set(i, "f");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        fButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_fButtonActionPerformed

    private void gButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gButtonActionPerformed
        if(letterList.contains('g')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('g')){
                        underscoreList.set(i, "g");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        gButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_gButtonActionPerformed

    private void hButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hButtonActionPerformed
        if(letterList.contains('h')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('h')){
                        underscoreList.set(i, "h");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        hButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_hButtonActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        if(letterList.contains('j')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('j')){
                        underscoreList.set(i, "j");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        jButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_jButtonActionPerformed

    private void kButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonActionPerformed
        if(letterList.contains('k')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('k')){
                        underscoreList.set(i, "k");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        kButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_kButtonActionPerformed

    private void lButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lButtonActionPerformed
        if(letterList.contains('l')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('l')){
                        underscoreList.set(i, "l");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        lButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_lButtonActionPerformed

    private void zButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zButtonActionPerformed
        if(letterList.contains('z')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('z')){
                        underscoreList.set(i, "z");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        zButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_zButtonActionPerformed

    private void xButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButtonActionPerformed
        if(letterList.contains('x')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('x')){
                        underscoreList.set(i, "x");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        xButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_xButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        if(letterList.contains('c')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('c')){
                        underscoreList.set(i, "c");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        cButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_cButtonActionPerformed

    private void vButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonActionPerformed
        if(letterList.contains('v')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('v')){
                        underscoreList.set(i, "v");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        vButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_vButtonActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        if(letterList.contains('b')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('b')){
                        underscoreList.set(i, "b");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        bButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_bButtonActionPerformed

    private void nButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nButtonActionPerformed
        if(letterList.contains('n')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('n')){
                        underscoreList.set(i, "n");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        nButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_nButtonActionPerformed

    private void mButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonActionPerformed
        if(letterList.contains('m')){
                for(int i = 0; i<letterList.size();i++){
                        if(letterList.get(i).equals('m')){
                        underscoreList.set(i, "m");
               }
       }
        }else{
            count++;
            changeImage();
        }
        jLabel3.setText(underscoreList.toString());
        mButton.setEnabled(false);
        isWin();      
    }//GEN-LAST:event_mButtonActionPerformed

        private void jButton28ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton28ActionPerformed
        {//GEN-HEADEREND:event_jButton28ActionPerformed
                jLabel3.setText(underscoreList.toString());                // TODO add your handling code here:
        }//GEN-LAST:event_jButton28ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hangman().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton aButton;
        private javax.swing.JButton bButton;
        private javax.swing.JButton cButton;
        private javax.swing.JButton dButton;
        private javax.swing.JButton eButton;
        private javax.swing.JButton fButton;
        private javax.swing.JButton gButton;
        private javax.swing.JButton hButton;
        private javax.swing.JButton iButton;
        private javax.swing.JButton jButton;
        private javax.swing.JButton jButton28;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private static javax.swing.JLabel jLabel3;
        private javax.swing.JButton kButton;
        private javax.swing.JButton lButton;
        private javax.swing.JButton mButton;
        private javax.swing.JButton nButton;
        private javax.swing.JButton oButton;
        private javax.swing.JButton pButton;
        private javax.swing.JButton qButton;
        private javax.swing.JButton rButton;
        private javax.swing.JButton sButton;
        private javax.swing.JButton tButton;
        private javax.swing.JButton uButton;
        private javax.swing.JButton vButton;
        private javax.swing.JButton wButton;
        private javax.swing.JButton xButton;
        private javax.swing.JButton yButton;
        private javax.swing.JButton zButton;
        // End of variables declaration//GEN-END:variables
}
