package Hangman;

/**
* Hangman/Hangman_InterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hangman.idl
* Thursday, May 10, 2018 3:54:56 PM SGT
*/

public final class Hangman_InterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Hangman.Hangman_Interface value = null;

  public Hangman_InterfaceHolder ()
  {
  }

  public Hangman_InterfaceHolder (Hangman.Hangman_Interface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Hangman.Hangman_InterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Hangman.Hangman_InterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Hangman.Hangman_InterfaceHelper.type ();
  }

}
