package Hangman;


/**
* Hangman/Hangman_InterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hangman.idl
* Thursday, May 10, 2018 3:54:30 PM SGT
*/

public interface Hangman_InterfaceOperations 
{
  boolean login (String name);
  String play (String name);
  void usedWord (String name, String word);
  String logout (String name);
} // interface Hangman_InterfaceOperations
