package Hangman;


/**
* Hangman/Hangman_Interface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hangman.idl
* Thursday, May 10, 2018 3:54:30 PM SGT
*/

public interface Hangman_Interface extends Hangman_InterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hangman_Interface
