# DO NOT EDIT THIS FILE!
#
# Python module Hangman generated by omniidl

import omniORB
omniORB.updateModule("Hangman")

# ** 1. Stub files contributing to this module
import Hangman_idl

# ** 2. Sub-modules

# ** 3. End
